# This is a basic workflow to help you get started with Actions

name: KWBupdate

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd KWBandage
          
          # UNUSED: git pull https://github.com/theHostileNegotiator/KWBandage.git master
          
          # Add the remote, call it "KWBandage":

          git remote add KWBandage https://github.com/theHostileNegotiator/KWBandage.git

          # Fetch all the branches of that remote into remote-tracking branches
          
          git fetch KWBandage
          
          # Make sure that you're on your master branch:
          
          git checkout master
          
          # Rewrite your master branch so that any commits of yours that
          # aren't already in upstream/master are replayed on top of that
          # other branch:
          
          git merge KWBandage/master
