# This is a basic workflow to help you get started with Actions

name: KWBupdate

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 */7 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
        
          # hack to get around not being able to figure out how to run an update on a remote repo when changes are detected
          rm -rf KWBandage
          
          # the following submodule commands work, but the files are pushed to /home/runner/work/KanesWrath-MODSDK-2020/KanesWrath-MODSDK-2020/KWBandage which I cannot locate
          # git submodule add https://github.com/theHostileNegotiator/KWBandage.git KWBandage
          # git submodule update --remote
          
          # do a simple clone (sorry GH servers)
          git remote add KWBandage https://github.com/theHostileNegotiator/KWBandage.git
          # git clone https://github.com/theHostileNegotiator/KWBandage.git KWBandage
          git pull KWBandage master

          ls
